```{r}
library('rethinking')
data(Howell1)
d = Howell1
d2= d[d$age>=18, ]
```
```{r}
precis(d)
```
Plot the mu prior

```{r}
curve(dnorm(x, 178, 20), from =100, to =250)
```

Plot the sigma prior
```{r}
curve(dunif(x, 0, 50), from=-10, to=60)
```

```{r}
x_bar = mean(d2$weight)

m4.3 = quap(alist(
  height ~ dnorm(mu, sigma),
  mu <- a + b * (weight - x_bar),
  a ~ dnorm(178, 20),
  b ~ dlnorm(0, 1),
  sigma ~ dunif(0, 50)
),
data = d2)
```
```{r}
summary(m4.3)
```
```{r}
round(vcov(m4.3), 3)
```

```{r}
pairs(m4.3)
```
```{r}
plot(height~weight, data=d2, col=rangi2)
post = extract.samples(m4.3)
a_map = mean(post$a)
b_map = mean(post$b)
curve(a_map+b_map*(x-x_bar), add=TRUE)

```

```{r}
mu=link(m4.3)
```
```{r}
weight.seq = seq(25, 70, .1)
sim.height=sim(m4.3, data=list(weight=weight.seq))
str(sim.height)
```

```{r}
height.PI = apply(sim.height, 2, PI, prob=0.89)
```

```{r}
post = extract.samples(m4.3)
mu.link = function(weight) post$a+post$b*(weight-x_bar)
mu = sapply(weight.seq, mu.link)
mu.mean = apply(mu, 2, mean)
mu.HPDI = apply(mu, 2, HPDI, prob=0.89)
plot(height~weight , d2, col=col.alpha(rangi2, 0.5))
lines(weight.seq, mu.mean)
shade(mu.HPDI, weight.seq)
shade(height.PI, weight.seq)

```

